services:
    app:
        build: .
        env_file: .env.docker
        volumes:
            - app_public:/app/public
            - app_storage:/app/storage
        depends_on:
            - postgres

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - app_public:/app/public:ro
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - /etc/letsencrypt:/etc/letsencrypt:ro
        depends_on:
            - app

    queue:
        build: .
        env_file: .env.docker
        entrypoint: []
        command: php artisan queue:work --tries=3 --timeout=60
        volumes:
            - app_storage:/app/storage
        depends_on:
            - postgres

    scheduler:
        build: .
        env_file: .env.docker
        entrypoint: []
        command: php artisan schedule:work
        volumes:
            - app_storage:/app/storage
        depends_on:
            - postgres

    postgres:
        image: postgres:16
        environment:
            POSTGRES_DB: pulsecheck
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ygoSFZIzErHs8Jkci7da23Sk6IO9MGy
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    app_public:
    app_storage:
    postgres_data:
