server {
    listen 80;
    server_name getpulsecheck.tech www.getpulsecheck.tech;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name getpulsecheck.tech www.getpulsecheck.tech;
    root /app/public;
    index index.php;

    ssl_certificate /etc/letsencrypt/live/getpulsecheck.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/getpulsecheck.tech/privkey.pem;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
